Expose set-pipeline errors by moving commands out of parameters
If pass or gcloud fails, we want the script to fail. So we need to move
the calls out of the ytt arguments and use vars instead

Co-authored-by: Kieron Browne <kbrowne@vmware.com>

diff --git a/pipelines/cf4k8s/set-pipeline b/pipelines/cf4k8s/set-pipeline
--- a/pipelines/cf4k8s/set-pipeline
+++ b/pipelines/cf4k8s/set-pipeline
@@ -28,13 +28,29 @@ if ! fly -t "$target" status &>/dev/null; then
   fly -t "$target" login
 fi
 
+# We want this script to exit with error if pass or gcloud fails rather than
+# silently interpolating an empty string into the pipeline vars!
+#
+# Assigning the subshell stdout to a variable preserves the expected semantics
+# of errexit, as these assignments are "simple commands" rather than
+# substitutions.
+#
+# This is a giant gotcha with shell scripts!
+# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01
+
+slack_webhook=$(pass eirini/ci/slack-webhook)
+dockerhub_password=$(pass eirini/docker-hub)
+private_keys_eirini_private_config=$(pass eirini/github/private-config/ssh-key)
+gcp_service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)
+gcp_dns_service_account_json=$(pass eirini/gcp-ci-dns-admin-json-key)
+
 ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
-  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
+  --data-value="slack.webhook=$slack_webhook" \
   --data-value="dockerhub.username=eiriniuser" \
-  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
-  --data-value="private_keys.eirini_private_config=$(pass eirini/github/private-config/ssh-key)" \
-  --data-value="gcp.service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
-  --data-value="gcp.dns_service_account_json=$(pass eirini/gcp-ci-dns-admin-json-key)" \
+  --data-value="dockerhub.password=$dockerhub_password" \
+  --data-value="private_keys.eirini_private_config=$private_keys_eirini_private_config" \
+  --data-value="gcp.service_account_json=$gcp_service_account_json" \
+  --data-value="gcp.dns_service_account_json=$gcp_dns_service_account_json" \
   --data-value="gcp.worker_count=$worker_count" \
   --data-value="gcp.cluster_name=$cluster_name" \
   --data-value="gcp.enable_windows_pool=$windows_pool" \
diff --git a/pipelines/ci-images/set-pipeline b/pipelines/ci-images/set-pipeline
--- a/pipelines/ci-images/set-pipeline
+++ b/pipelines/ci-images/set-pipeline
@@ -16,10 +16,23 @@ if ! fly -t "$target" status &>/dev/null; then
   fly -t "$target" login
 fi
 
+# We want this script to exit with error if pass or gcloud fails rather than
+# silently interpolating an empty string into the pipeline vars!
+#
+# Assigning the subshell stdout to a variable preserves the expected semantics
+# of errexit, as these assignments are "simple commands" rather than
+# substitutions.
+#
+# This is a giant gotcha with shell scripts!
+# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01
+
+slack_webhook=$(pass eirini/ci/slack-webhook)
+dockerhub_password=$(pass eirini/docker-hub)
+
 ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
-  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
+  --data-value="slack.webhook=$slack_webhook" \
   --data-value="dockerhub.username=eiriniuser" \
-  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
+  --data-value="dockerhub.password=$dockerhub_password" \
   >"$pipeline_yml"
 
 noColor=
diff --git a/pipelines/ci/set-pipeline b/pipelines/ci/set-pipeline
--- a/pipelines/ci/set-pipeline
+++ b/pipelines/ci/set-pipeline
@@ -25,16 +25,34 @@ if ! fly -t "$target" status &>/dev/null; then
   fly -t "$target" login
 fi
 
-eirini_release_private_key=$(pass eirini/github/eirini-release/ssh-key)
+# We want this script to exit with error if pass or gcloud fails rather than
+# silently interpolating an empty string into the pipeline vars!
+#
+# Assigning the subshell stdout to a variable preserves the expected semantics
+# of errexit, as these assignments are "simple commands" rather than
+# substitutions.
+#
+# This is a giant gotcha with shell scripts!
+# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01
+
+slack_webhook=$(pass eirini/ci/slack-webhook)
+dockerhub_username=eiriniuser
+dockerhub_password=$(pass eirini/docker-hub)
+private_keys_eirini=$(pass eirini/github/eirini/ssh-key)
+private_keys_eirini_release=$(pass eirini/github/eirini-release/ssh-key)
+private_keys_eirini_private_config=$(pass eirini/github/private-config/ssh-key)
+gcp_service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)
+wiremock_keystore_pass=$(pass eirini/ci/wiremock-keystore-password)
+
 ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
-  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
+  --data-value="slack.webhook=$slack_webhook" \
   --data-value="dockerhub.username=eiriniuser" \
-  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
-  --data-value="private_keys.eirini=$(pass eirini/github/eirini/ssh-key)" \
-  --data-value="private_keys.eirini_release=$eirini_release_private_key" \
-  --data-value="private_keys.eirini_private_config=$(pass eirini/github/private-config/ssh-key)" \
-  --data-value="gcp.service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
-  --data-value="wiremock_keystore_pass=$(pass eirini/ci/wiremock-keystore-password)" \
+  --data-value="dockerhub.password=$dockerhub_password" \
+  --data-value="private_keys.eirini=$private_keys_eirini" \
+  --data-value="private_keys.eirini_release=$private_keys_eirini_release" \
+  --data-value="private_keys.eirini_private_config=$private_keys_eirini_private_config" \
+  --data-value="gcp.service_account_json=$gcp_service_account_json" \
+  --data-value="wiremock_keystore_pass=$wiremock_keystore_pass" \
   --data-value="gcp.worker_count=$worker_count" \
   --data-value="repo_branches.eirini=$working_branch" \
   --data-value="repo_branches.eirini_ci=$ci_branch" \
diff --git a/pipelines/egg/set-pipeline b/pipelines/egg/set-pipeline
--- a/pipelines/egg/set-pipeline
+++ b/pipelines/egg/set-pipeline
@@ -16,21 +16,45 @@ if ! fly -t "$target" status &>/dev/null; then
   fly -t "$target" login
 fi
 
+# We want this script to exit with error if pass or gcloud fails rather than
+# silently interpolating an empty string into the pipeline vars!
+#
+# Assigning the subshell stdout to a variable preserves the expected semantics
+# of errexit, as these assignments are "simple commands" rather than
+# substitutions.
+#
+# This is a giant gotcha with shell scripts!
+# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01
+
+slack_webhook=$(pass eirini/ci/slack-webhook)
+dockerhub_password=$(pass eirini/docker-hub)
+private_keys_eirinidotcf=$(pass eirini/github/eirinidotcf/ssh-key)
+private_keys_eirini_private_config=$(pass eirini/github/private-config/ssh-key)
+gcp_service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)
+postfacto_mysql_address=$(gcloud --project cff-eirini-peace-pods sql instances describe postfacto-cf4k8s4a8e --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')
+postfacto_mysql_password=$(pass show eirini/postfacto-cf4k8s4a8e/mysql-admin-password)
+jefe_github_oauth_client_id=$(pass eirini/jefe/client-id)
+jefe_github_oauth_client_secret=$(pass eirini/jefe/client-secret)
+jefe_db_password=$(pass eirini/jefe/dbuser-pass)
+jefe_db_address=$(gcloud sql instances describe jefe-db --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')
+jefe_admin_password=$(pass eirini/jefe/admin-pass)
+pairup_firebase_conf=$(pass eirini/pairup/conf.js)
+
 ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
-  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
+  --data-value="slack.webhook=$slack_webhook" \
   --data-value="dockerhub.username=eiriniuser" \
-  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
-  --data-value="private_keys.eirinidotcf=$(pass eirini/github/eirinidotcf/ssh-key)" \
-  --data-value="private_keys.eirini_private_config=$(pass eirini/github/private-config/ssh-key)" \
-  --data-value="gcp.service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
-  --data-value="postfacto.mysql.address=$(gcloud --project cff-eirini-peace-pods sql instances describe postfacto-cf4k8s4a8e --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')" \
-  --data-value="postfacto.mysql.password=$(pass show eirini/postfacto-cf4k8s4a8e/mysql-admin-password)" \
-  --data-value="jefe.github_oauth.client_id=$(pass eirini/jefe/client-id)" \
-  --data-value="jefe.github_oauth.client_secret=$(pass eirini/jefe/client-secret)" \
-  --data-value="jefe.db.password=$(pass eirini/jefe/dbuser-pass)" \
-  --data-value="jefe.db.address=$(gcloud sql instances describe jefe-db --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')" \
-  --data-value="jefe.admin_password=$(pass eirini/jefe/admin-pass)" \
-  --data-value="pairup.firebase_conf=$(pass eirini/pairup/conf.js)" \
+  --data-value="dockerhub.password=$dockerhub_password" \
+  --data-value="private_keys.eirinidotcf=$private_keys_eirinidotcf" \
+  --data-value="private_keys.eirini_private_config=$private_keys_eirini_private_config" \
+  --data-value="gcp.service_account_json=$gcp_service_account_json" \
+  --data-value="postfacto.mysql.address=$postfacto_mysql_address" \
+  --data-value="postfacto.mysql.password=$postfacto_mysql_password" \
+  --data-value="jefe.github_oauth.client_id=$jefe_github_oauth_client_id" \
+  --data-value="jefe.github_oauth.client_secret=$jefe_github_oauth_client_secret" \
+  --data-value="jefe.db.password=$jefe_db_password" \
+  --data-value="jefe.db.address=$jefe_db_address" \
+  --data-value="jefe.admin_password=$jefe_admin_password" \
+  --data-value="pairup.firebase_conf=$pairup_firebase_conf" \
   >"$pipeline_yml"
 
 noColor=
