Format all scripts
[#160919054]

Signed-off-by: Georgi Dankov <gddankov@gmail.com>

diff --git a/scripts/docker b/scripts/docker
--- a/scripts/docker
+++ b/scripts/docker
@@ -2,7 +2,7 @@
 
 # Start Docker Daemon (and set a trap to stop it once this script is done)
 start-docker() {
-  echo 'DOCKER_OPTS="--data-root /scratch/docker --max-concurrent-downloads 10"' > /etc/default/docker
+  echo 'DOCKER_OPTS="--data-root /scratch/docker --max-concurrent-downloads 10"' >/etc/default/docker
   service docker start
   trap 'service docker stop' EXIT
 
@@ -11,8 +11,8 @@ start-docker() {
   until docker-running; do
     echo "Current docker status: $(service docker status)"
     if [ "$current_retries" -gt "$max_retries" ]; then
-        echo "Failed to start docker daemon after $max_retries retries"
-        exit 1
+      echo "Failed to start docker daemon after $max_retries retries"
+      exit 1
     fi
     ((++current_retries))
     sleep 0.5
@@ -21,6 +21,5 @@ start-docker() {
 }
 
 docker-running() {
-  docker stats --no-stream > /dev/null 2>&1
+  docker stats --no-stream >/dev/null 2>&1
 }
-
